# Generated by Django 4.2 on 2023-05-01 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('breizhcamp_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='artist',
        ),
        migrations.RemoveField(
            model_name='release',
            name='song',
        ),
        migrations.AddField(
            model_name='release',
            name='song',
            field=models.ManyToManyField(help_text='Select a song for this release', to='breizhcamp_app.song'),
        ),
    ]
